### ISSUE TITLE
Use nunique

### ISSUE THREAD

**Issue by sen1** [yuunaK/intro-data-capstone-biodiversity#1]
https://github.com/yuunaK/intro-data-capstone-biodiversity/blob/271477e13af1bf097085ee5824626b8eb9231fba/Yuuna_Mathew_Biodiversity_Capstone/biodiversity3.py#L103-L105

As the instruction mentioned, count the number of species at each conservation level. If you have a column where top to bottom ['cow','cow','dog'] then count() would return 3 because it counts all non-null values. nunique() on the other hand would return 2. Since you were asked for number of species, you will need to disregard the repetitions. 

species.groupby('conservation_status').scientific_name.nunique().reset_index()

**Comment by yuunaK** [comment]
Abhisek,

Again I thank you for your comment but again, I did this for my own sake to
see the difference.  As far as the report is concerned, I would not use
this information.  I think I might have mentioned in my comment 'Check the
above values'.... as I was workign with the dataset, i wanted to explore
the extent of the difference between count and nunique.  If you notice, I
use both methods.
