### ISSUE TITLE
No need

### ISSUE THREAD

**Issue by sen1** [yuunaK/intro-data-capstone-biodiversity#2]
https://github.com/yuunaK/intro-data-capstone-biodiversity/blob/271477e13af1bf097085ee5824626b8eb9231fba/Yuuna_Mathew_Biodiversity_Capstone/biodiversity3.py#L111-L124

This is exactly what we dont want to. Imagine you have unknown number of conservation_status values. If you would like to count each group you can just use groupby:

species.groupby('conservation_status').scientific_name.nunique().reset_index()

**Comment by yuunaK** [comment]
Abhisek,

I did this as a comparison for my own sake, to see the nature of the
difference.
