### ISSUE TITLE
Alternate method

### ISSUE THREAD

**Issue by sen1** [yuunaK/intro-data-capstone-biodiversity#4]
https://github.com/yuunaK/intro-data-capstone-biodiversity/blob/271477e13af1bf097085ee5824626b8eb9231fba/Yuuna_Mathew_Biodiversity_Capstone/biodiversity3.py#L224

Here is a alternate easy method to achieve the same:
species['is_protected'] = species.conservation_status != 'No Intervention'

Another important note is x != 'No Intervention' returns a boolean. So you dont need an extra True/False if statement.

**Comment by yuunaK** [comment]
This is the same issue as Issue 5.  I know in coding, that simplicity is best.  Whittling away all extraneous bits of code is really important when you want to write clean, efficient, elegant code.  So I do appreciate your making this point. At this point of my learning, I really find it less mentally cumbersome to just see what is going on with a piece of code.
